using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyConfigurationAttribute("Release - No Tests")]
[assembly: AssemblyCompanyAttribute("Paul Kohler")]
[assembly: AssemblyCopyrightAttribute("Copyright (C) 2005-2009 Paul Kohler")]

