#region License

// Copyright 2005-2009 Paul Kohler (http://pksoftware.net/MiniSqlQuery/). All rights reserved.
// This source code is made available under the terms of the Microsoft Public License (Ms-PL)
// http://minisqlquery.codeplex.com/license
#endregion

using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
[assembly: ComVisible(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyCompanyAttribute("Paul Kohler")]
[assembly: AssemblyCopyrightAttribute("Copyright (C) 2005-2009 Paul Kohler")]