IF OBJECT_ID('TABLE_NAME', 'U') IS NOT NULL
  DROP TABLE TABLE_NAME

CREATE TABLE TABLE_NAME
(
	TABLE_NAMEId INT IDENTITY NOT NULL, 
    CONSTRAINT PK_TABLE_NAMEId PRIMARY KEY (TABLE_NAMEId)
)
