//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniSqlQuery.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiniSqlQuery.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINI SQL QUERY LICENSE
        ///PK Software - Paul Kohler
        ///paul@pksoftware.net
        ///
        ///----------------------------------------------------------------------
        ///
        ///Microsoft Public License (Ms-PL)
        ///
        ///This license governs use of the accompanying software. If you use the software, you accept this license. If you do not accept the license, do not use the software.
        ///
        ///1. Definitions
        ///
        ///The terms &quot;reproduce,&quot; &quot;reproduction,&quot; &quot;derivative works,&quot; and &quot;distribution&quot; have the same meaning here as under U.S. copyright law.
        ///
        ///A &quot;con [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LicenseMiniSqlQuery {
            get {
                return ResourceManager.GetString("LicenseMiniSqlQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;SyntaxDefinition name = &quot;SQL&quot; extensions = &quot;.sql&quot;&gt;
        ///	&lt;Digits name = &quot;Digits&quot; bold = &quot;true&quot; italic = &quot;false&quot; color = &quot;Blue&quot;/&gt;
        ///	&lt;RuleSets&gt;
        ///		&lt;RuleSet ignorecase = &quot;true&quot;&gt;
        ///			&lt;Delimiters&gt;&amp;amp;&amp;lt;&amp;gt;~!%^*()-+=|\#/{}[]:;&quot;&apos; ,	.?&lt;/Delimiters&gt;
        ///			&lt;Span name=&quot;String&quot; bold=&quot;false&quot; italic=&quot;false&quot; color=&quot;Red&quot; stopateol=&quot;false&quot;&gt;
        ///				&lt;Begin&gt;&apos;&lt;/Begin&gt;
        ///				&lt;End&gt;&apos;&lt;/End&gt;
        ///			&lt;/Span&gt;
        ///			&lt;Span name = &quot;LineComment&quot; bold = &quot;false&quot; italic = &quot;false&quot; color = &quot;Green&quot; stopateol = &quot;true&quot;&gt;
        ///				&lt;Begin&gt;- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlModeXshd {
            get {
                return ResourceManager.GetString("SqlModeXshd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        internal static string TemplatesDirectoryName {
            get {
                return ResourceManager.GetString("TemplatesDirectoryName", resourceCulture);
            }
        }
    }
}
