//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniSqlQuery.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiniSqlQuery.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not populate with current connection string - .
        /// </summary>
        internal static string BindNewConnectionStringBuilder_Could_not_populate_with_current_connection_string___ {
            get {
                return ResourceManager.GetString("BindNewConnectionStringBuilder_Could_not_populate_with_current_connection_string_" +
                        "__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to &apos;{0}&apos; successfully..
        /// </summary>
        internal static string Connected_to_0_successfully {
            get {
                return ResourceManager.GetString("Connected_to_0_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Failed.
        /// </summary>
        internal static string Connection_Failed {
            get {
                return ResourceManager.GetString("Connection_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Successful.
        /// </summary>
        internal static string Connection_Successful {
            get {
                return ResourceManager.GetString("Connection_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed connecting to &apos;{0}&apos;.{1}{2}.
        /// </summary>
        internal static string Failed_connecting_to_0_1_2 {
            get {
                return ResourceManager.GetString("Failed_connecting_to_0_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                    GNU LESSER GENERAL PUBLIC LICENSE
        ///                       Version 3, 29 June 2007
        ///					   
        /// Copyright (C) 2007 Free Software Foundation, Inc. &lt;https://fsf.org/&gt;
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///
        ///  This version of the GNU Lesser General Public License incorporates
        ///the terms and conditions of version 3 of the GNU General Public
        ///License, supplemented by the additional permissions listed below.
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LicenseMiniSqlQuery {
            get {
                return ResourceManager.GetString("LicenseMiniSqlQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;Mini SQL Query Read Me&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		h1, h2, h3, h4
        ///		{
        ///			font-family: Verdana;
        ///		}
        ///		blockquote, p, ul, ol, li
        ///		{
        ///			font-family: Verdana;
        ///			font-size: small;
        ///		}
        ///	&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h3&gt;
        ///		Mini SQL Query
        ///	&lt;/h3&gt;
        ///	&lt;blockquote&gt;
        ///		&lt;p&gt;
        ///			&quot;&lt;b&gt;Mini SQL Query&lt;/b&gt; from by Paul Kohler  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadMe {
            get {
                return ResourceManager.GetString("ReadMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Connection?.
        /// </summary>
        internal static string Reload_Connection {
            get {
                return ResourceManager.GetString("Reload_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes?.
        /// </summary>
        internal static string Save_Changes {
            get {
                return ResourceManager.GetString("Save_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!-- 
        ///Copyright 2005-2019 Paul Kohler (https://github.com/paulkohler/minisqlquery). All rights reserved.
        ///This source code is made available under the terms of the GNU Lesser General Public License v3.0
        ///https://github.com/paulkohler/minisqlquery/blob/master/LICENSE
        ///--&gt;
        ///&lt;SyntaxDefinition name = &quot;SQL&quot; extensions = &quot;.sql&quot;&gt;
        ///	&lt;Properties&gt;
        ///		&lt;Property name=&quot;LineComment&quot; value=&quot;--&quot;/&gt;
        ///	&lt;/Properties&gt;
        ///	&lt;Digits name = &quot;Digits&quot; bold = &quot;true&quot; italic = &quot;false&quot; color = &quot;Blue&quot;/&gt;
        ///	&lt;RuleSets&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlModeXshd {
            get {
                return ResourceManager.GetString("SqlModeXshd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table: .
        /// </summary>
        internal static string Table_colon {
            get {
                return ResourceManager.GetString("Table_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table: (none).
        /// </summary>
        internal static string Table_none {
            get {
                return ResourceManager.GetString("Table_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        internal static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        internal static string TemplatesDirectoryName {
            get {
                return ResourceManager.GetString("TemplatesDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection details have changed, do you want to save?
        ///.
        /// </summary>
        internal static string The_connection_details_have_changed__do_you_want_to_save {
            get {
                return ResourceManager.GetString("The_connection_details_have_changed__do_you_want_to_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connections have changed, would you like to refresh the database connection?.
        /// </summary>
        internal static string The_connections_have_changed__would_you_like_to_refresh_the_database_connection {
            get {
                return ResourceManager.GetString("The_connections_have_changed__would_you_like_to_refresh_the_database_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Data.
        /// </summary>
        internal static string ViewData {
            get {
                return ResourceManager.GetString("ViewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Data Error.
        /// </summary>
        internal static string ViewDataError {
            get {
                return ResourceManager.GetString("ViewDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        internal static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
    }
}
